#ifndef CIC_ERROR_H
#define CIC_ERROR_H

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
  CIC_SUCCESS = 0,
  CIC_ERROR_INVALID_PARAMETER,
  CIC_ERROR_OUT_OF_MEMORY,
  CIC_ERROR_UNSUPPORTED_FORMAT,
  CIC_ERROR_DECODE_FAILED,
  CIC_ERROR_ENCODE_FAILED,
  CIC_ERROR_FILE_NOT_FOUND,
  CIC_ERROR_FILE_READ_FAILED,
  CIC_ERROR_FILE_WRITE_FAILED,
  CIC_ERROR_INVALID_DIMENSIONS,
  CIC_ERROR_CORRUPTED_DATA,
  CIC_ERROR_CANCELLED,
  CIC_ERROR_RESOURCE_LIMIT,
  CIC_ERROR_UNKNOWN_FORMAT,
} CICError;

#ifdef __cplusplus
}
#endif

#endif /* CIC_ERROR_H */
